Added request-based logging with X-REQUEST-LOG-LEVEL
Skatteetaten/aurora-springboot2-starter pull request #6
Opened 2018-08-30 11:15 UTC by Corvwyn

2018-08-31 06:50 UTC, bjartek requested changes

2018-08-31 06:50 UTC, bjartek commented on src/main/java/no/skatteetaten/aurora/logging/MdcRequestFilter.java
> +@ConditionalOnProperty(prefix = "aurora.starter.requestbasedlogging", name = "enabled")
Mangler det en matchIfMissing="false" her? Hva skjer hvis du ikke har satt aurora.starter.requestbasedlogging.enabled?

2018-09-26 15:42 UTC, Corvwyn commented
@bentsolheim @bjartek 
Jeg snakket med Tom, og han hadde en ide til forbedring av denne funksjonaliteten. Man vil gjerne ha debug/trace-logging mens en prosess kjører, gjerne med flere kall. Hadde det vært nyttig å sette hvor lang periode man vil ha endret LogLevel, istedenfor en frysperiode på en enkel request?

Eksempel:
Man setter X-REQUEST-LOG-LEVEL til debug. Man vil da få debug-logging i f.eks. 5 sekunder (requestbasedlogging.duration). Etter 5 sekunder har gått, må man vente 30 sekunder (requestbasedlogging.wait) før man kan gjøre dette igjen.

2018-10-11 11:08 UTC, bjartek commented
Hva gjør vi med denne? Det viser seg jo at vi ikke kan legge turbo filter i base image. Skal vi ha det i aurora-logbback.xml? Kan vi jobbe oss rundt at vi ikke kan ha det i den globale logback filen?

2019-03-19 08:58 UTC, closed without merging